language: node_js
node_js:
- '0.10'
env:
#- NODE_ENV=development
- LAIKA_OPTIONS="-t 5000"
services:
  - mongodb
branches:
  only:
  - master
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install -g laika phantomjs jshint
script:
- echo "Running tests and hinting"
- jshint ./
after_success:
- meteor deploy inspire-me.meteor.com
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: always
    on_failure: always