language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install --development
script:
- echo Running tests and hinting
- npm run jshint
- chmod +x ./makeRTDTestsWorkInTravis.sh && ./makeRTDTestsWorkInTravis.sh
- npm run test
after_success:
- cd app/
- meteor build --directory ../deploy
- cd ../
before_deploy:
- rm -rf app
- rm -rf node_modules
- rm -rf test
- cd deploy/bundle/programs/server
- npm install
- cd ../../../../
deploy:
  provider: heroku
  app: inspire-me-dev
  strategy: anvil
  skip_cleanup: true
  api_key:
    secure: vMSuLcI2rzDVWBxsb7FcsVYBtIO13iLhnn7rWIG09Rd5dRG0hFJljpmi8FPKrL1ynF9RNn7vVEBIb1LZb+e/+Dn93gaeceIgXb9FbTQHALJju0lzyQ/FgsgKf8CU3tEnWiAu9rHKc+idR7pH7As/A+zQeoxiC2WuE8br+a36NTw=
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: always
    on_failure: always
