language: node_js
node_js:
- '0.10'
env:
#- NODE_ENV=development
branches:
  only:
  - master
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install
script:
- echo "Running tests and hinting"
- npm run jshint
- npm run test
after_success:
- meteor deploy inspire-me.meteor.com
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: always
    on_failure: always