language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
  - develop
services:
  - mongodb
env: 
  - LAIKA_OPTIONS="-t 5000"
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install --development
script:
- echo Running tests and hinting
- npm run jshint
#- npm test //////// laika is broken in it's current version so skip this for now
before_deploy:
- 'bash -c "cd app && meteor build --directory ../deploy"'
- rm -rf app
- rm -rf node_modules
- 'bash -c "cd deploy/bundle/programs/server && npm install"'
- npm install --production
deploy:
  provider: heroku
  app: 
    develop: inspire-me-dev
    master: inspire-me-live
  strategy: api
  skip_cleanup: true
  api_key:
    secure: vMSuLcI2rzDVWBxsb7FcsVYBtIO13iLhnn7rWIG09Rd5dRG0hFJljpmi8FPKrL1ynF9RNn7vVEBIb1LZb+e/+Dn93gaeceIgXb9FbTQHALJju0lzyQ/FgsgKf8CU3tEnWiAu9rHKc+idR7pH7As/A+zQeoxiC2WuE8br+a36NTw=
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: change
    on_failure: change
