language: node_js
node_js:
- '0.10'
env: 
branches:
  only:
  - master
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install
script:
- echo Running tests and hinting
- npm run jshint
- chmod +x ./makeRTDTestsWorkInTravis.sh && ./makeRTDTestsWorkInTravis.sh
- npm run test
after_success:
- cd app/
- meteor deploy inspire-me.meteor.com
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: always
    on_failure: always
deploy:
  provider: heroku
  app: inspire-me-dev
  api_key:
    secure: vMSuLcI2rzDVWBxsb7FcsVYBtIO13iLhnn7rWIG09Rd5dRG0hFJljpmi8FPKrL1ynF9RNn7vVEBIb1LZb+e/+Dn93gaeceIgXb9FbTQHALJju0lzyQ/FgsgKf8CU3tEnWiAu9rHKc+idR7pH7As/A+zQeoxiC2WuE8br+a36NTw=
