language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
  - develop
services:
- mongodb
env:
- LAIKA_OPTIONS="-t 5000"
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install --development
script:
- echo Running tests and hinting
- npm run jshint
before_deploy:
- bash -c "cd app && meteor build --directory ../deploy"
- rm -rf app
- rm -rf node_modules
- bash -c "cd deploy/bundle/programs/server && npm install"
- npm install --production
deploy:
  provider: heroku
  app:
    develop: inspire-me-dev
    master: inspire-me-live
  strategy: api
  skip_cleanup: true
  api_key:
    secure: RBNskLVHmvviRQZd9qiDGfkSdwsq9/Q/+ns2z+ilXa0gcSnDcYUvx7Ynh/eZcSZm2NIpkz5C3MmdG8pTwOtyl25N+g5eqD0jlWsmwIE4TtQ+3bJk0paNxi8Uh3ulL6ddi6KQgtI5DLbJnkzT26WI+Oj2tT3U3B/5NtMsd+3gmkQ=
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    - heydon@neontribe.co.uk
    on_sucess: change
    on_failure: change
